export const FETCHING_SHOP_SUCCESS = 'FETCHING_SHOP_SUCCESS';
export const FETCHING_SHOP_FAILURE = 'FETCHING_SHOP_FAILURE';
export const DEL_SHOP_SUCCESS = 'DEL_SHOP_SUCCESS';
export const DEL_SHOP_FAILURE = 'DEL_SHOP_FAILURE';
export const PASS_SHOP_SUCCESS = 'PASS_SHOP_SUCCESS';
export const PASS_SHOP_FAILURE = 'PASS_SHOP_FAILURE';
